#!/usr/bin/env node
// Builds a loadable extension directory per browser.
//
// The repo root holds the shared source plus three manifest fragments:
//   manifest.base.json     — keys identical across browsers
//   manifest.firefox.json  — sidebar_action, background.scripts, gecko settings
//   manifest.chrome.json   — side_panel, background.service_worker
//
// `node scripts/build.mjs` merges base + <browser> into dist/<browser>/manifest.json
// and copies the shipped file set alongside it. Shipped files come from an explicit
// allowlist (not an ignore list) so a new local-only directory can never leak into
// a build — the old `web-ext --ignore-files` approach packaged anything it hadn't
// been told to exclude.

import { readFile, writeFile, mkdir, rm, cp, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');

export const BROWSERS = ['firefox', 'chrome'];

// Keys that must be REPLACED wholesale by the per-browser fragment rather than
// deep-merged. `background` is the one that matters: merging Firefox's
// { scripts } with Chrome's { service_worker } would emit both and break both.
const REPLACE_KEYS = new Set(['background']);

function mergeManifest(base, override) {
  const out = { ...base };
  for (const [key, value] of Object.entries(override)) {
    const prev = base[key];
    if (REPLACE_KEYS.has(key)) {
      out[key] = value;
    } else if (Array.isArray(value)) {
      // Permissions and host_permissions are sets — concat and dedupe so a
      // fragment adds to the shared list instead of clobbering it.
      out[key] = [...new Set([...(Array.isArray(prev) ? prev : []), ...value])];
    } else if (value && typeof value === 'object' && prev && typeof prev === 'object' && !Array.isArray(prev)) {
      out[key] = mergeManifest(prev, value);
    } else {
      out[key] = value;
    }
  }
  return out;
}

export async function buildManifest(browser) {
  const base = JSON.parse(await readFile(path.join(ROOT, 'manifest.base.json'), 'utf8'));
  const override = JSON.parse(await readFile(path.join(ROOT, `manifest.${browser}.json`), 'utf8'));
  return mergeManifest(base, override);
}

// Every file that ships inside the packaged extension. Root-level *.js is the
// whole extension source (build tooling lives in scripts/, tests in tests/),
// so globbing it is complete without being a catch-all over the repo.
export async function shippedFiles() {
  const rootJs = (await readdir(ROOT))
    .filter(f => f.endsWith('.js'))
    .sort();
  return [...rootJs, 'popup.html', 'popup.css', 'icons'];
}

// ─── Chrome: browser.* polyfill ──────────────────────────────────────────────
// The source uses the promise-based `browser.*` namespace throughout (~360
// call sites). Firefox provides it natively; Chrome does not, so every script
// would throw ReferenceError on its first line. Rather than rewrite the call
// sites, the Chrome build loads Mozilla's polyfill ahead of everything else.
//
// Injected at build time rather than checked into the shared source, so the
// Firefox build stays byte-for-byte free of it.
export const POLYFILL = 'browser-polyfill.js';
const POLYFILL_SRC = path.join(ROOT, 'node_modules', 'webextension-polyfill', 'dist', 'browser-polyfill.js');

// ─── Background: load order ──────────────────────────────────────────────────
// The background is several files sharing one global scope (Chrome via
// importScripts below, Firefox via manifest background.scripts). This array is
// the source of truth for the order; manifest.firefox.json repeats it, and
// tests/background-split.test.mjs fails if the two ever disagree.
//
// Only bg-core.js executes anything at load time — it holds the listener
// registrations and the capability flags everything else reads. The rest are
// pure declarations and could be listed in any order; they're kept in
// dependency-ish order for readability, not correctness.
export const BACKGROUND_FILES = [
  'bg-core.js',
  'bg-auth.js',
  'bg-gsc.js',
  'bg-ga.js',
  'bg-page.js',
  'bg-ads.js',
  'bg-webceo.js',
  'bg-export.js',
  'bg-clients.js',
  'bg-router.js'
];

// Chrome's service_worker takes a single file, so this thin entry point pulls
// in the polyfill ahead of the background files. Keeping those files uncopied
// preserves their line numbers in stack traces.
const SW_ENTRY = 'sw.js';
const SW_SOURCE = `// Generated by scripts/build.mjs — do not edit.\n`
  + `importScripts(${[POLYFILL, ...BACKGROUND_FILES].map(f => `'${f}'`).join(', ')});\n`;

async function addPolyfill(outDir, manifest) {
  if (!existsSync(POLYFILL_SRC)) {
    throw new Error(`webextension-polyfill not installed — run \`npm ci\` (looked in ${POLYFILL_SRC})`);
  }
  await cp(POLYFILL_SRC, path.join(outDir, POLYFILL));
  await writeFile(path.join(outDir, SW_ENTRY), SW_SOURCE);

  // Content scripts load in array order, so the polyfill has to come first.
  for (const cs of manifest.content_scripts || []) {
    if (cs.js && !cs.js.includes(POLYFILL)) cs.js.unshift(POLYFILL);
  }

  // Same for the panel: prepend a tag before the first existing <script>.
  const htmlPath = path.join(outDir, 'popup.html');
  const html = await readFile(htmlPath, 'utf8');
  const firstScript = html.indexOf('<script src=');
  if (firstScript === -1) throw new Error('popup.html has no <script src> to anchor the polyfill to');
  await writeFile(
    htmlPath,
    html.slice(0, firstScript) + `<script src="${POLYFILL}"></script>\n  ` + html.slice(firstScript)
  );
}

async function build(browser) {
  const outDir = path.join(DIST, browser);
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const manifest = await buildManifest(browser);

  for (const entry of await shippedFiles()) {
    const src = path.join(ROOT, entry);
    if (!existsSync(src)) throw new Error(`${browser}: shipped file missing from repo — ${entry}`);
    await cp(src, path.join(outDir, entry), { recursive: true });
  }

  // Mutates `manifest` (content_scripts), so it must run before the write.
  if (browser === 'chrome') await addPolyfill(outDir, manifest);

  await writeFile(path.join(outDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

  return { browser, outDir, version: manifest.version };
}

// Only run when invoked directly, so the tests can import the helpers above.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const arg = process.argv.find(a => a.startsWith('--browser='));
  const targets = arg ? [arg.split('=')[1]] : BROWSERS;

  for (const browser of targets) {
    if (!BROWSERS.includes(browser)) {
      console.error(`Unknown browser "${browser}" — expected one of: ${BROWSERS.join(', ')}`);
      process.exit(1);
    }
    const { outDir, version } = await build(browser);
    console.log(`built ${browser} v${version} → ${path.relative(ROOT, outDir)}/`);
  }
}
